### ISSUE TITLE
Add support for reloading the model database

### ISSUE THREAD

**Issue by jug-dev** [hlky/nataili#142]
In long running processes that use nataili (like a stable horde worker) the model database may be updated long after we have instantiated the library.

There appears to be no nice way to cause the nataili library to redownload a fresh model database. Simply restarting the process isn't a great solution if we're using voodoo to load 120 models which take an hour to reload.

**Comment by db0** [comment]
Looks to me to redownload the model reference is as simple as calling init on the compvis modelmanager inside the suprer model manager

**Comment by hlky** [comment]
[c196f28](https://github.com/hlky/nataili/commit/c196f2899e1ed1e24891ac6467d673d13a385ef7)

[`reload_database()`](https://github.com/hlky/nataili/blob/c196f2899e1ed1e24891ac6467d673d13a385ef7/nataili/model_manager/super.py#L127)
