### ISSUE TITLE
Prevent multiple threads from trying to handle high power jobs at the same time

### ISSUE THREAD

**Issue by CrypticWit** [hlky/nataili#64]
Currently, the max_power setting for workers seems to be on a per thread basis. This is generally fine, except for when your worker picks up two or more high power requests at the same time (such as high resolution in-painting). This can cause one of the requests to fail due to a lack of VRAM.

Some mechanism to either pause threads during complex tasks, or reduce the max_power they are able to accept, would prevent this from happening.

**Comment by djstrikanova** [comment]
Maybe sum power of all parallel threads and if it exceeds a threshold disable one or more threads until it's below that threshold.

**Comment by hlky** [comment]
Can be reraised at [db0/AI-Horde-Worker](https://github.com/db0/AI-Horde-Worker)
